spring:
  application:
    name: lecture
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
    host: localhost
    port: 6379
    password: 1q2w3e4r

  # ?? ??
  logging:
    level:
      root: info
      org:
        hibernate:
          SQL: debug
        springframework:
          web: debug