spring:
  application:
    name: lecture
  datasource:
    # DB_CLOSE_DELAY=-1 ?????? ??? ?? ?? ?????? ????, DB_CLOSE_ON_EXIT=FALSE ?????? ?? ? ??????? ?? ???? ??
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
  redis:
    lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
    host: localhost
    port: 6379
    password: 1q2w3e4r

  # ?? ??
  logging:
    level:
      root: info
      org:
        hibernate:
          SQL: debug
        springframework:
          web: debug